using System;
using System.Collections.Generic;

namespace RoslynRepl.Editor.Core
{
    /// <summary>
    /// Issue #63: session-only named pins for live values. `_` is
    /// useful but holds exactly one value; debugging often wants
    /// `player`, `manager`, `popup` available simultaneously without
    /// re-typing accessors. Pins are stored in process memory only —
    /// a domain reload, an Editor restart, or Reset Project Data
    /// clears them, matching the acceptance criterion that pins are
    /// "session-only or clearly marked as session-only."
    ///
    /// The wrapper class generated by <see cref="ReplCodeWrapper"/>
    /// emits each pin as a `dynamic` static property pulling through
    /// to <see cref="Get"/>, so snippets and Watch expressions can
    /// reference a pinned name unqualified — exactly like the
    /// existing `_` carry-over.
    ///
    /// Pin name validation is exposed as <see cref="ValidateName"/>:
    /// names must be valid C# identifiers (letter / underscore start,
    /// letter / digit / underscore continue) and not collide with
    /// the wrapper's reserved tokens (`_`, `ct`) or any C# keyword.
    /// The reserved-set check is the small drift-prone bit — if
    /// <see cref="ReplCodeWrapper"/> introduces another well-known
    /// static the wrapper relies on, add it here too.
    /// </summary>
    public static class PinStore
    {
        // Reference-tracking dictionary keyed by name. Insertion order
        // is preserved so the UI surfaces pins in the order the user
        // created them rather than re-sorting on every mutation.
        private static readonly Dictionary<string, object> _pins =
            new Dictionary<string, object>(StringComparer.Ordinal);
        private static readonly List<string> _names = new List<string>();

        /// <summary>Raised after any mutation (Set / Remove / Clear).
        /// The host subscribes to invalidate <see cref="ReplEngine"/>'s
        /// compile cache so a follow-up Run / Watch refresh sees the
        /// pin set the user just edited, not the cached pre-edit
        /// wrapper source.</summary>
        public static event Action Changed;

        /// <summary>Names in insertion order. Returned as a fresh
        /// snapshot so a UI iterating while the store is mutated
        /// doesn't see a moving target.</summary>
        public static IReadOnlyList<string> Names => _names.ToArray();

        public static int Count => _names.Count;

        public static bool Has(string name)
            => !string.IsNullOrEmpty(name) && _pins.ContainsKey(name);

        /// <summary>
        /// Read a pin by name. Returns null when the pin doesn't
        /// exist *and* when the stored value happens to be null — the
        /// wrapper's `dynamic` property type collapses both cases
        /// uniformly (`null.member` throws NRE at the use site, which
        /// is the same diagnostic the user would get from an `_`
        /// access against a null carry-over).
        /// </summary>
        public static object Get(string name)
        {
            if (string.IsNullOrEmpty(name)) return null;
            return _pins.TryGetValue(name, out var v) ? v : null;
        }

        /// <summary>Snapshot of every pin (name + boxed value) for
        /// the Pins window. Returns a list of tuples in insertion
        /// order; the caller can format or filter as it pleases.
        /// Returns a fresh list each call so iteration during edit
        /// is safe.</summary>
        public static List<(string Name, object Value)> Snapshot()
        {
            var result = new List<(string, object)>(_names.Count);
            foreach (var n in _names)
            {
                _pins.TryGetValue(n, out var v);
                result.Add((n, v));
            }
            return result;
        }

        /// <summary>
        /// Set or replace a pin. Returns true on success. Returns
        /// false + populates <paramref name="error"/> when the name
        /// fails validation; callers surface the message verbatim in
        /// the input dialog or as a warning toast.
        /// </summary>
        public static bool TrySet(string name, object value, out string error)
        {
            if (!ValidateName(name, out error)) return false;
            bool isUpdate = _pins.ContainsKey(name);
            _pins[name] = value;
            if (!isUpdate) _names.Add(name);
            Changed?.Invoke();
            return true;
        }

        /// <summary>Drop a single pin. Returns true iff the pin
        /// existed and was removed; the Changed event fires only on
        /// real removals.</summary>
        public static bool Remove(string name)
        {
            if (string.IsNullOrEmpty(name)) return false;
            if (!_pins.Remove(name)) return false;
            _names.Remove(name);
            Changed?.Invoke();
            return true;
        }

        /// <summary>Wipe every pin. No-op (and no Changed fire) when
        /// the store is already empty so a repeated Clear / Reset
        /// Project Data click doesn't churn the compile cache for
        /// nothing.</summary>
        public static void Clear()
        {
            if (_pins.Count == 0) return;
            _pins.Clear();
            _names.Clear();
            Changed?.Invoke();
        }

        /// <summary>
        /// Validate a candidate pin name. Returns true on success;
        /// returns false + sets <paramref name="error"/> to a
        /// user-facing message on failure. Rules:
        /// <list type="bullet">
        /// <item>non-empty after trim</item>
        /// <item>valid C# identifier — letter/_ first, then letter/
        ///       digit/_</item>
        /// <item>not a C# keyword (full reserved list, including
        ///       contextual keywords like <c>var</c> / <c>dynamic</c>
        ///       that would shadow user intent if wrapper-injected)</item>
        /// <item>not one of the wrapper's reserved statics
        ///       (<c>_</c>, <c>ct</c>) — those are already filled by
        ///       <see cref="ReplEngine"/>'s carry-over and the
        ///       cancellation token, and a pin sharing the name
        ///       would silently mask the engine's value</item>
        /// </list>
        /// </summary>
        public static bool ValidateName(string name, out string error)
        {
            error = null;
            if (string.IsNullOrWhiteSpace(name))
            {
                error = "Pin name can't be empty.";
                return false;
            }
            if (!IsValidIdentifier(name))
            {
                error = "Pin name must be a valid C# identifier (letters, digits, underscores; first char letter or underscore).";
                return false;
            }
            if (_reservedWrapperStatics.Contains(name))
            {
                error = $"`{name}` is reserved by the REPL wrapper. Pick a different name.";
                return false;
            }
            if (_cSharpKeywords.Contains(name))
            {
                error = $"`{name}` is a C# keyword. Pick a different name.";
                return false;
            }
            return true;
        }

        private static bool IsValidIdentifier(string s)
        {
            if (string.IsNullOrEmpty(s)) return false;
            char first = s[0];
            if (!(char.IsLetter(first) || first == '_')) return false;
            for (int i = 1; i < s.Length; i++)
            {
                char c = s[i];
                if (!(char.IsLetterOrDigit(c) || c == '_')) return false;
            }
            return true;
        }

        // Tokens the wrapper already uses. A pin sharing one of
        // these would either silently mask load-bearing semantics
        // (`_` = LastResult, `ct` = cancellation token) or — worse
        // for the method / class names — produce a wrapper
        // member-name collision that fails *every* Run / Watch
        // compile until the user finds and removes that pin.
        //
        // The two name constants are pulled off ReplCodeWrapper so
        // a future rename of either flows through here without a
        // second-place update. The two property names (`_`, `ct`)
        // are still spelled out since the wrapper writes them as
        // bare source, not via constants.
        private static readonly HashSet<string> _reservedWrapperStatics =
            new HashSet<string>(StringComparer.Ordinal)
            {
                "_",
                "ct",
                ReplCodeWrapper.ClassName,
                ReplCodeWrapper.MethodName,
            };

        // C# 12 keyword set (excluding contextual keywords that are
        // legal as identifiers in non-contextual positions — `var` /
        // `dynamic` / `record` are flagged because a wrapper-injected
        // `dynamic dynamic` static would be a parse-time disaster).
        // SyntaxFacts.GetKeywordKind would be authoritative but
        // depends on Roslyn types we don't reference from Core; a
        // hardcoded snapshot trades currency for zero coupling.
        private static readonly HashSet<string> _cSharpKeywords =
            new HashSet<string>(StringComparer.Ordinal)
            {
                "abstract","as","base","bool","break","byte","case","catch","char",
                "checked","class","const","continue","decimal","default","delegate",
                "do","double","else","enum","event","explicit","extern","false",
                "finally","fixed","float","for","foreach","goto","if","implicit",
                "in","int","interface","internal","is","lock","long","namespace",
                "new","null","object","operator","out","override","params","private",
                "protected","public","readonly","ref","return","sbyte","sealed",
                "short","sizeof","stackalloc","static","string","struct","switch",
                "this","throw","true","try","typeof","uint","ulong","unchecked",
                "unsafe","ushort","using","virtual","void","volatile","while",
                // Contextual keywords whose injection would still
                // shadow user intent or fail at the wrapper site.
                "var","dynamic","async","await","yield","nameof","record",
            };
    }
}
